site_name: AI Engineer 2025
site_description: AI Engineer 2025
site_author: Lekhraj Dinkar
docs_dir: docs
nav:
    - Agentic AI:
        - Introduction : 02_agentic_ai/00_agentic-ai-start.md
        - MCP protocol ðŸ”¸ : 02_agentic_ai/01_MCP.md
        - A2A protocol ðŸ”¸: 02_agentic_ai/02_A2A.md
        - context Engineering: 02_agentic_ai/04_context_engineering.md

    - AWS Certification Note:

        - Generative AI(1): 00_temp/01_GenAI.md
        - Generative AI(2): 00_temp/02_start.md
        - 01_bedrock: 01_aws/01_bedrock.md
        - 02_sageMaker: 01_aws/02_sageMaker.md
        - Machine learning: 00_temp/04_AI_ML.md
        - Deep learning: 00_temp/04_Deep-learning.md
        - AI challenges: 00_temp/05_AI_challenges.md
        - Prompt Engineering: 00_temp/03_prompt_engineering.md

    - POCs:
        - 01 chatbot: 98_poc/poc_1_cb.md
        - 02 RAG with dynamoDB: 98_poc/poc_2_rag.md

theme:
  name: material
  features:
    - navigation.tracking          # Enables breadcrumbs
    - navigation.tabs              # Optional: if using tabs layout
    - navigation.top               # Scroll-to-top button
    - navigation.sections
    #- navigation.expand
    - navigation.indexes
    - navigation.footer            # Enables next/previous at bottom
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: pink
  custom_dir: .

extra_css:
  - mkdocs.css

repo_url: https://github.com/lekhrajdinkar/genai
repo_name: GitHub
edit_uri: edit/main/Notes/

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lekhrajdinkar
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lekhraj-dinkar-25872140/