site_name: System Engineering -  Notes
site_description: System Engineering -  Notes
site_author: Lekhraj
docs_dir: docs

extra_javascript:
  - mkdocs.js

# Navigation based on your Notes folder
nav:
    - Traditional AI + theory:
        - ðŸ”°2025:
            - Start: 00_gen_ai/00_temp/00_start.md
            - Generative AI: 00_gen_ai/00_temp/00_GenAI.md
            - ML Machine learning: 00_gen_ai/00_temp/04_AI_ML.md
            - AI challenges: 00_gen_ai/00_temp/05_AI_challenges.md
    - New AI (genAI):
        - ðŸ”°2025:
            - Prompting: 00_gen_ai/00_temp/03_prompt_engineering.md
            - Agentic AI:
              - Introduction : 00_gen_ai/02_agentic_ai/00_start.md
              - AI Tools encountered : 00_gen_ai/02_agentic_ai/03_tried.md
              - MCP protocol ðŸ”¸ : 00_gen_ai/02_agentic_ai/01_MCP.md
              - A2A protocol ðŸ”¸: 00_gen_ai/02_agentic_ai/02_A2A.md
            - POCs:
              - 01 chatbot: 00_gen_ai/poc/poc_1_cb.md
              - 02 RAG with dynamoDB: 00_gen_ai/poc/poc_2_rag.md
    - AWS:
        - ðŸ”°2025:
          - 01_bedrock: 00_gen_ai/01_aws/01_bedrock.md
          - 02_sageMaker: 00_gen_ai/01_aws/02_sageMaker.md

theme:
  name: material
  features:
    - navigation.tracking          # Enables breadcrumbs
    - navigation.tabs              # Optional: if using tabs layout
    - navigation.top               # Scroll-to-top button
    - navigation.sections
    #- navigation.expand
    - navigation.indexes
    - navigation.footer            # Enables next/previous at bottom
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: pink
  custom_dir: .

extra_css:
  - mkdocs.css

repo_url: https://github.com/lekhrajdinkar/genai
repo_name: GitHub
edit_uri: edit/main/Notes/

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lekhrajdinkar
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lekhraj-dinkar-25872140/